name: Copy folder to other branch

on: 
  push:
    branches:
    - main

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy
        env:
          SRC_FOLDER_PATH: 'public'
          TARGET_BRANCH: 'gh-pages'
        run: |
          git subtree push --prefix $SRC_FOLDER_PATH main $TARGET_BRANCH
