# A workflow that copy the file inside the public folder into gh-pages branch
name: Deploy to gh-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
